/// Reads the golden corpus — the cross-language contract this package must satisfy.
///
/// The corpus is generated from the TypeScript implementation and frozen. Both languages replay the
/// same cases through their own driver and must produce identical `(sql, params)` for every dialect.
/// See `goldens/README.md`.
///
/// The JSON is embedded rather than read from disk because these tests must run under **dart2js**
/// as well as the VM, and `dart:io` does not exist on the web. `test/conformance/corpus_data.dart`
/// is generated by `dart run tool/embed_goldens.dart`.
library;

import 'dart:convert';

const dialects = ['mssql', 'mysql', 'postgres', 'sqlite'];

/// A value supplied *into* a query, carrying its type tag.
///
/// The tag is load-bearing. JSON cannot distinguish `5` from `5.0`, but Dart can — and a `double`
/// whose value is integral must still render as `5`, not `5.0`, to match what JavaScript emits. A
/// driver that decodes `{"t":"double","v":5}` into a Dart `int` has thrown away the very thing the
/// corpus is testing.
Object? decodeInputValue(Map<String, Object?> value) {
  final tag = value['t'] as String;
  switch (tag) {
    case 'null':
      return null;
    case 'string':
      return value['v'] as String;
    case 'int':
      return (value['v'] as num).toInt();
    case 'double':
      // MUST be a real double, even when the JSON number is integral. This is the case that catches
      // a port which renders `5.0` as "5.0" (Flutter mobile) or declares it `@p0 float`.
      return (value['v'] as num).toDouble();
    case 'bool':
      return value['v'] as bool;
    case 'datetime':
      return DateTime.parse(value['v'] as String).toUtc();
    case 'json':
      // The corpus tags JSON blobs for documentation. The TypeScript driver's `toValue()` has no
      // `json` arm, so the value is `undefined` and binds as NULL — which the golden records.
      return null;
    default:
      throw StateError('corpus: unknown input value tag "$tag"');
  }
}

/// Encodes a bound parameter for comparison against the golden.
///
/// Numbers are tagged `num`, not `int`/`double`: at the driver boundary no dialect distinguishes an
/// integral double from an int, JavaScript cannot even observe the difference, and Dart's
/// `5 == 5.0` is true. The int/double distinction is pinned where it is observable — in the SQL
/// *text* — which the golden `sql` strings capture exactly.
Map<String, Object?> encodeOutputValue(Object? value) {
  if (value == null) {
    return {'t': 'null'};
  }
  if (value is String) {
    return {'t': 'string', 'v': value};
  }
  if (value is num) {
    return {'t': 'num', 'v': value};
  }
  if (value is bool) {
    return {'t': 'bool', 'v': value};
  }
  if (value is DateTime) {
    return {'t': 'datetime', 'v': value.toUtc().toIso8601String()};
  }
  return {'t': 'json', 'v': jsonEncode(value)};
}

class GoldenCase {
  GoldenCase(this.name, this.note, this.ops, this.builders, this.transaction,
      this.dialects, this.expect);

  factory GoldenCase.fromJson(Map<String, Object?> json) => GoldenCase(
        json['name']! as String,
        json['note'] as String?,
        (json['ops'] as List<Object?>?)?.cast<Map<String, Object?>>(),
        (json['builders'] as List<Object?>?)?.cast<Map<String, Object?>>(),
        json['transaction'] as String?,
        (json['dialects'] as List<Object?>?)?.cast<String>(),
        (json['expect']! as Map<String, Object?>).cast<String, Object?>(),
      );

  final String name;
  final String? note;
  final List<Map<String, Object?>>? ops;
  final List<Map<String, Object?>>? builders;
  final String? transaction;
  final List<String>? dialects;
  final Map<String, Object?> expect;

  List<String> get targetDialects => dialects ?? const [...dialects_];
  static const dialects_ = ['mssql', 'mysql', 'postgres', 'sqlite'];
}

class Corpus {
  Corpus(this.version, this.cases);

  factory Corpus.parse(String source) {
    final json = jsonDecode(source) as Map<String, Object?>;
    return Corpus(
      json['version']! as String,
      (json['cases']! as List<Object?>)
          .map((c) => GoldenCase.fromJson(c! as Map<String, Object?>))
          .toList(),
    );
  }

  final String version;
  final List<GoldenCase> cases;
}
