import 'dart:convert';
import 'dart:io';

/// Embeds `goldens/corpus.json` into `test/conformance/corpus_data.dart` as a Dart constant.
///
///     dart run tool/embed_goldens.dart
///
/// The conformance tests must run under **dart2js** as well as the Dart VM — that is the only way
/// to catch the number divergence between Flutter web and Flutter mobile — and `dart:io` does not
/// exist on the web, so the corpus cannot be read from disk there. Embedding it is the simplest
/// thing that works on both platforms.
void main() {
  final source = File('goldens/corpus.json').readAsStringSync();

  // Base64, not a raw string literal. The corpus is full of SQL with doubled quotes (`''why?''`),
  // which puts `'''` sequences in the text and terminates a Dart triple-quoted string early. Base64
  // has no such hazard, needs no escaping, and decodes identically on the VM and under dart2js.
  final encoded = base64.encode(utf8.encode(source));

  // Four-space continuation indent, matching what `dart format` produces for adjacent string
  // literals — so the generated file is format-stable and never churns CI's format check. (The
  // `// dart format off` directive is not an option: it needs language version >= 3.8, and this
  // package's SDK floor is lower.)
  final chunks = <String>[];
  for (var i = 0; i < encoded.length; i += 96) {
    chunks.add(
        "    '${encoded.substring(i, (i + 96).clamp(0, encoded.length))}'");
  }

  final out = File('test/conformance/corpus_data.dart');
  out.writeAsStringSync('''
// GENERATED by `dart run tool/embed_goldens.dart` — do not edit.
//
// The golden corpus, embedded so the conformance suite can run under dart2js (where dart:io, and
// therefore reading a file, does not exist). Regenerate after `dart run tool/fetch_goldens.dart`.
//
// Base64 because the corpus contains SQL with doubled quotes, which would terminate a Dart raw
// string early.

import 'dart:convert';

/// The golden corpus JSON.
String get corpusJson => utf8.decode(base64.decode(_corpusBase64));

const _corpusBase64 =
${chunks.join('\n')};
''');

  stdout.writeln(
      'Embedded ${source.length} bytes (${encoded.length} base64) into ${out.path}');
}
